name: Deploy via FTP

on:
  push:
    branches: [main]
  # Allows to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository using git
        uses: actions/checkout@v5
      - name: Install, build, and upload site output
        uses: radenpioneer/astro-ftp-deploy@v0.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          directory: astro/
          package-manager: npm
